# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(438, 565)
        MainWindow.setStyleSheet("QPushButton {\n"
"background-color: aqua;\n"
"color:steelblue;\n"
"font-size: 20px;\n"
"border: 3px solid indigo;\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: blue;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 0, 131, 71))
        self.label.setStyleSheet("QLabel {\n"
"background-color: aqua;\n"
"color:steelblue;\n"
"font-size: 20px;\n"
"border: 3px solid indigo;\n"
"border-radius: 15px;\n"
"}\n"
"QLabel:hover{\n"
"background-color: blue;\n"
"\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 80, 221, 71))
        self.label_2.setStyleSheet("QLabel {\n"
"background-color: aqua;\n"
"color:steelblue;\n"
"font-size: 20px;\n"
"border: 3px solid indigo;\n"
"border-radius: 15px;\n"
"}\n"
"QLabel:hover{\n"
"background-color: blue;\n"
"\n"
"}")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 170, 241, 61))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"background-color: aqua;\n"
"color:steelblue;\n"
"font-size: 20px;\n"
"border: 3px solid indigo;\n"
"border-radius: 15px;\n"
"}\n"
"QLineEdit:hover{\n"
"background-color: blue;\n"
"\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 240, 241, 61))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"background-color: aqua;\n"
"color:steelblue;\n"
"font-size: 20px;\n"
"border: 3px solid indigo;\n"
"border-radius: 15px;\n"
"}\n"
"QLineEdit:hover{\n"
"background-color: blue;\n"
"\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 310, 241, 61))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"background-color: aqua;\n"
"color:steelblue;\n"
"font-size: 20px;\n"
"border: 3px solid indigo;\n"
"border-radius: 15px;\n"
"}\n"
"QLineEdit:hover{\n"
"background-color: blue;\n"
"\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(100, 390, 131, 41))
        self.checkBox.setStyleSheet("QCheckBox {\n"
"background-color: aqua;\n"
"color:steelblue;\n"
"font-size: 20px;\n"
"border: 3px solid indigo;\n"
"border-radius: 15px;\n"
"}\n"
"QCheckBox:hover{\n"
"background-color: blue;\n"
"\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 440, 141, 51))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 438, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sign up"))
        self.label_2.setText(_translate("MainWindow", "Enter your information"))
        self.lineEdit.setText(_translate("MainWindow", "username"))
        self.lineEdit_2.setText(_translate("MainWindow", "password"))
        self.lineEdit_3.setText(_translate("MainWindow", "confirm password"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton.setText(_translate("MainWindow", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
